name: StrikeSurrender
version: '${project.version}'
main: dev.iiahmed.strikesurrender.StrikeSurrender
authors: [ iiAhmedYT ]
description: '${project.description}'
commands:
  surrender:
    description: 'The command that allows you to give your opponent the win by leaving your match'
    aliases:
      - forfeit
      - ff
      - concede
      - leavefight
      - leavematch
      - retreat
      - withdraw
      - giveup
      - givein
      - yield